CicekSepeti/Models/Table/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CicekSepeti.Models.Table
{
    [Table("Catagory")]
    public class Category
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        [StringLength(100)]
        public string name { get; set; }

        public int? count { get; set; }

        public int? TopCategoryid{ get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public   virtual TopCategory TopCategory { get; set; }

    }
    
}

CicekSepeti/Models/Table/Order.cs
using CicekSepeti.Models.Table.others;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CicekSepeti.Models.Table
{
    [Table("Order")]
    public class Order
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public string kargo  { get; set; }
        public string mail { get; set; }
        public string adres { get; set; }
        public int? couponTotal { get; set; }
        public int? total { get; set; }
        public DateTime? date { get; set; }
        public int? status { get; set; }
        //public int invoiceid { get; set; }
        //public int cargoid { get; set; }
        public int? Cartid { get; set; }
        public int? Invoiceid { get; set; }
        public int? Userid { get; set; }

        public virtual Invoice Invoice { get; set; }



        public virtual List< OrderDetail> detail { get; set; }
        public virtual Cart Cart { get; set; }
        public virtual User User { get; set; }
       

     
    }
}

CicekSepeti/Models/Table/Product.cs
using CicekSepeti.Models.Table.others;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CicekSepeti.Models.Table
{
    [Table("Product")]
    public class Product
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public int?  productcode{ get; set; }
        [StringLength(100)]
        public string name { get; set; }
        [StringLength(100)]
        public string explanation { get; set; }

        public int price { get; set; }
        public int? stock { get; set; }

        public string image { get; set; }
        public string status { get; set; }
        public int count { get; set; }
        //public int Staticticsid { get; set; }
        public int? CategoryID { get; set; }
        public int? ProductDetailid { get; set; }

        public virtual Category Category { get; set; }
        public virtual ProductDetail ProductDetail{ get; set; }
       


     
 
        



    }


}

CicekSepeti/Models/Table/Statistics/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CicekSepeti.Models.Table.Statistics
{
    public class Product:Statistics
    {
      
        public int productid { get; set; }
        public int Producstid { get; set; }

        Product Products = new Product();

    }
}

CicekSepeti/Models/Table/User.cs
using CicekSepeti.Models.Table.others;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CicekSepeti.Models.Table
{
    [Table("User")]
    public class User
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        [StringLength(100)]
        public string mail { get; set; }

        public string password { get; set; }
        public string adress { get; set; }
        public string username { get; set; }

        public bool? acvtive { get; set; }

        public bool? verfication { get; set; }
        public DateTime? birthday { get; set; }
        public DateTime? lastlogin { get; set; }
        public DateTime? registertime { get; set; }

    
        public int? status { get; set; }
        //public int Staticticsid { get; set; }
        public virtual WishList WishList { get; set; }
        public virtual List<Order> Order{ get; set; }







    }

}

CicekSepeti/Controllers/NEDController.cs
using CicekSepeti.Models.Database;
using CicekSepeti.Models.Table;
using CicekSepeti.Models.Table.others;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CicekSepeti.Controllers
{
    public class NEDController : Controller
    {
        BaseData db = new BaseData();
        Category category = new Category();
        Product product = new Product();
        OrderDetail OrderDetail = new OrderDetail();
        // GET: NED
        public ActionResult CategoryEdit(int? id)
        {
            category = db.CatogoryDbTable.Where(x => x.id == id).FirstOrDefault();
         
            return View(category);
        }
        public ActionResult CategoryNew()
        {
            return View();
        }
        public ActionResult CategoryDelete(int? id)
        {
            category = db.CatogoryDbTable.Where(x => x.id == id).FirstOrDefault();

            return View(category);
        }
        public ActionResult ProductEdit(int? id)
        {
            product = db.ProductDbTable.Where(x => x.id == id).FirstOrDefault();

            return View(product);
        }
        public ActionResult ProductNew()
        {
            return View();
        }
        public ActionResult ProductDelete(int? id)
        {
            product = db.ProductDbTable.Where(x => x.id == id).FirstOrDefault();

            return View(product);
        }
        public ActionResult OrderEdit(int? id)
        {
            OrderDetail = db.OrderDetailTable.Where(x => x.id == id).FirstOrDefault();

            return View(OrderDetail);
        }
        public ActionResult OrderNew()
        {
            return View();
        }
        public ActionResult OrderDelete(int? id)
        {
            OrderDetail = db.OrderDetailTable.Where(x => x.id == id).FirstOrDefault();

            return View(OrderDetail);
        }
        public ActionResult UserEdit(int? id)
        {
            return View();
        }
        public ActionResult UserNew()
        {
            return View();
        }
        public ActionResult UserDelete(int? id)
        {
            return View();
        }
       
        //Post
    }
}

CicekSepeti/Controllers/OrderController.cs
using CicekSepeti.Models.Database;
using CicekSepeti.Models.Model;
using CicekSepeti.Models.Table;
using CicekSepeti.Models.Table.others;

using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CicekSepeti.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        
        public ActionResult LogIn()
        {
            return View();
        }
        public ActionResult Order()
        {
            
            Product product = new Product();
  

            object objProduct = Session["sepet"];
            OrderAndProduct OP = new OrderAndProduct();
            OP.Product = (Product)objProduct;
        
            //deneme amaclı
            product.id = 1;
            product.name = "deneme";
            OP.Product = product;
            objProduct = 1;
            //

            Response.Write("0");
            if (objProduct != null)
                return View (OP);
            else
            {

                return RedirectToAction("LogIn", "Order");
            }
        }
        [HttpPost]
        public ActionResult Control(OrderDetail order)
        {

            Session.Add("Orderdetail",order);
            return RedirectToAction("OrderNote", "Order");

            ///return Json(false);

        }
        public ActionResult OrderNote()
        {

            return View();
        }
        
        [HttpPost]
        public ActionResult OrderNoteControl(OrderDetail order)
        {

            OrderDetail detail = new OrderDetail();
            detail = (OrderDetail)Session["Orderdetail"];
            detail.Note = order.Note;
           
            Session["Orderdetail"] = detail;
            return RedirectToAction("Information", "Order");
        }

       
        public ActionResult Information()
        {
            return View();
        }
        [HttpPost]
        public ActionResult InformationControl(Invoice ınvoice)
        {

            Session.Add("Invoice", ınvoice);
            return RedirectToAction("OrderPay","Order");
        }
        public ActionResult OrderPay()
        {
            return View();
        }
        [HttpPost]
        public ActionResult OrderPayControl(Invoice ınvoice)
        {

            //Invoice inv = new Invoice();
            //inv = (Invoice)Session["Invoice"];
            //inv.name = order.Note;
            //inv.tel= order.NoteName;
            //inv.mail= order.NoteActive;
            //Session["Invoice"] = detail;
            return RedirectToAction("veritabaninagiris", "Order");

        }
        public ActionResult veritabaninagiris()
        {
            Invoice ınvoice = new Invoice();
            OrderDetail detail = new OrderDetail();
            BaseData db = new BaseData();

            ınvoice = (Invoice)Session["Invoice"];
            detail = (OrderDetail)Session["OrderDetail"];




            db.InvoiceTable.Add(ınvoice);
            db.OrderDetailTable.Add(detail);
            db.SaveChanges();
            Session.Remove("OrderDetail");
            Session.Remove("Invoice");
            return RedirectToAction("Products","ProductPage");
        }


    }
}

CicekSepeti/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CicekSepeti.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult LogIn()
        {
            return View();
        }
        public ActionResult UserLogin()
        {

            return View();
        }  
        public ActionResult OrderNote()
        {

            return View();
        }     
    
     
        public ActionResult Information()
        {
            return View();
        } 
        public ActionResult OrderPay()
        {
            return View();
        }
 
        public ActionResult OrderTrack()
        {
            return View();
        }
        public ActionResult Support()
        {
            return View();
        }
    }
}

CicekSepeti/Views/Admin/Category.cshtml
@model List<CicekSepeti.Models.Table.Category> 
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/LayoutPage/LayoutAdmin.cshtml";
}

<div class="">



    <div class="row">
        <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        KATEGORİ TABLOSU
                        <br />
                        KATEGORİ SAYISI: @Model.Count

                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#">Settings 1</a>
                                <a class="dropdown-item" href="#">Settings 2</a>
                            </div>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>


                <div class="x_content">

                    <div class="row">
                        @Html.ActionLink("Yeni Ekle", "CategoryNew", "NED", new { }, new { @class = "btn btn-success" })
                        <div class="col-sm-12">
                            <div class="card-box table-responsive">
                                <p class="text-muted font-13 m-b-30">
                                    HIZLI GÖSTERİM KATEGORİ
                                </p>

                                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                                    <thead>
                                        <tr>
                                            <th>ÜRÜN İD</th>
                                            <th>ÜRÜN ADI</th>
                                            <th>KATAGORİ</th>
                                            <th></th>




                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var ktgr in Model)
                                        {


                                            <tr>
                                                <td>@ktgr.id</td>
                                                <td>@ktgr.name</td>


                                                @*<td>  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a></td>*@


                                                <td>    <a href="@Url.Action("CategoryEdit","NED",new { id=ktgr.id })" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a></td>
                                                <td>  <a href="@Url.Action("CategoryDelete","NED",new { id=ktgr.id })" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> SİL </a></td>

                                            </tr>
                                        }

                                    </tbody>

                                </table>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CicekSepeti/Views/Admin/Orders.cshtml
@model List<CicekSepeti.Models.Table.others.OrderDetail>
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/LayoutPage/LayoutAdmin.cshtml";
}

<div class="">



    <div class="row">
        <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        KATEGORİ TABLOSU
                        <br />
                        KATEGORİ SAYISI: @Model.Count

                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#">Settings 1</a>
                                <a class="dropdown-item" href="#">Settings 2</a>
                            </div>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>


                <div class="x_content">

                    <div class="row">
                        @Html.ActionLink("Yeni Ekle", "OrderNew", "NED", new { }, new { @class = "btn btn-success" })
                        <div class="col-sm-12">
                            <div class="card-box table-responsive">
                                <p class="text-muted font-13 m-b-30">
                                    HIZLI GÖSTERİM KATEGORİ
                                </p>

                                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                                    <thead>
                                        <tr>
                                            <th>ÜRÜN İD</th>
                                            <th>ÜRÜN ADI</th>
                                            <th>KATAGORİ</th>
                                            <th></th>




                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {


                                            <tr>
                                                <td>@item.id</td>
                                                <td>@item.name</td>


                                                @*<td>  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a></td>*@


                                                <td>    <a href="@Url.Action("Orderedit","NED",new { id=item.id })" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a></td>
                                                <td>  <a href="@Url.Action("Orderdelete","NED",new { id=item.id })" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> SİL </a></td>

                                            </tr>
                                        }

                                    </tbody>

                                </table>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CicekSepeti/Views/Admin/Products.cshtml
@model List<CicekSepeti.Models.Table.Product>
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/LayoutPage/LayoutAdmin.cshtml";
}

<div class="">



    <div class="row">
        <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        KATEGORİ TABLOSU
                        <br />
                        KATEGORİ SAYISI: @Model.Count

                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#">Settings 1</a>
                                <a class="dropdown-item" href="#">Settings 2</a>
                            </div>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>


                <div class="x_content">

                    <div class="row">
                        @Html.ActionLink("Yeni Ekle", "ProductNew", "NED", new { }, new { @class = "btn btn-success" })
                        <div class="col-sm-12">
                            <div class="card-box table-responsive">
                                <p class="text-muted font-13 m-b-30">
                                    HIZLI GÖSTERİM KATEGORİ
                                </p>

                                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                                    <thead>
                                        <tr>
                                            <th>ÜRÜN İD</th>
                                            <th>ÜRÜN ADI</th>
                                            <th>KATAGORİ</th>
                                            <th></th>




                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {


                                            <tr>
                                                <td>@item.id</td>
                                                <td>@item.name</td>


                                                @*<td>  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a></td>*@


                                                <td>    <a href="@Url.Action("Productedit","NED",new { id=item.id })" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a></td>
                                                <td>  <a href="@Url.Action("Productdelete","NED",new { id=item.id })" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> SİL </a></td>

                                            </tr>
                                        }

                                    </tbody>

                                </table>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CicekSepeti/Views/Admin/Users.cshtml
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/LayoutPage/LayoutAdmin.cshtml";
}

<div class="">



    <div class="row">
        <div class="col-md-12 col-sm-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        KATEGORİ TABLOSU
                        <br />
                        KATEGORİ SAYISI: @Model.Count

                    </h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#">Settings 1</a>
                                <a class="dropdown-item" href="#">Settings 2</a>
                            </div>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>


                <div class="x_content">

                    <div class="row">
                        @Html.ActionLink("Yeni Ekle", "newkatagori", "NED", new { }, new { @class = "btn btn-success" })
                        <div class="col-sm-12">
                            <div class="card-box table-responsive">
                                <p class="text-muted font-13 m-b-30">
                                    HIZLI GÖSTERİM KATEGORİ
                                </p>

                                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                                    <thead>
                                        <tr>
                                            <th>ÜRÜN İD</th>
                                            <th>ÜRÜN ADI</th>
                                            <th>KATAGORİ</th>
                                            <th></th>




                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var ktgr in Model)
                                        {


                                            <tr>
                                                <td>@ktgr.id</td>
                                                <td>@ktgr.name</td>


                                                @*<td>  <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a></td>*@


                                                <td>    <a href="@Url.Action("katagoriedit","NED",new { id=ktgr.id })" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a></td>
                                                <td>  <a href="@Url.Action("katagoridelete","NED",new { id=ktgr.id })" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> SİL </a></td>

                                            </tr>
                                        }

                                    </tbody>

                                </table>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>